import React from "react";
import electroniccar from "../../../public/eletronic-car.png";
import illustration from "../../../public/illustration-electric-car.png";
import metering from "../../../public/virtual-net-metering.png";
import minclude from "../../../public/metering-include.png";
import Image from "next/image";

const Resource = () => {
  return (
    <div>
      <h1 className="font-bold text-3xl text-center text-[#344DA3] mt-5">
        Resource
      </h1>
      <div className="flex flex-col md:flex-row items-center justify-center w-full p-8">
        <div className="w-full md:w-1/2 p-4">
          <Image src={electroniccar} alt="leading" />
        </div>
        <div className="w-full md:w-1/2 p-4">
          <h1 className="mb-8 font-bold text-xl md:text-2xl lg:text-3xl">
            What is Net Metering?
          </h1>
          <p className="text-sm md:text-base lg:text-lg">
            Net metering is a billing arrangement that allows homeowners and
            businesses with renewable energy systems, such as solar panels, to
            receive credit for the excess electricity they generate and feed
            back into the grid. Under a net metering program, a bi-directional
            meter tracks the energy generated by the renewable energy system and
            the energy consumed by the customer. If the customer generates more
            electricity than they consume, the excess electricity is fed back
            into the grid and credited to their account. This credit can then be
            used to offset the cost of electricity that is consumed during
            periods when the renewable energy system is not generating
            electricity, such as at night or on cloudy days. Net metering
            policies vary by state and country, but it is a popular policy in
            many regions that encourage the adoption of renewable energy
            technologies.
          </p>
        </div>
      </div>

      <div className="p-8">
        <h1 className="font-bold mb-8">Benefits of Net Metering</h1>
        <ul className="list-disc leading-7 mb-3">
          <li>
            Financial savings: Net metering allows homeowners and businesses to
            generate their own electricity and receive credit for the excess
            electricity they generate, which can help to offset their
            electricity bills. This can result in significant financial savings
            over time.
          </li>
        </ul>
        <ul className="list-disc leading-7 mb-3">
          <li>
            Increased use of renewable energy: Net metering can encourage the
            adoption of renewable energy systems, such as solar panels, by
            making them more financially viable. This can help to reduce
            reliance on fossil fuels and promote a transition to cleaner energy
            sources.
          </li>
        </ul>
        <ul className="list-disc leading-7 mb-3">
          <li>
            Reduced greenhouse gas emissions: By promoting the use of renewable
            energy, net metering can help to reduce greenhouse gas emissions and
            mitigate the impacts of climate change.
          </li>
        </ul>
        <ul className="list-disc leading-7 mb-3">
          <li>
            Improved grid stability: Net metering can help to improve grid
            stability by reducing the strain on the grid during peak demand
            periods. This is because excess electricity generated by solar
            panels can be fed back into the grid, helping to balance the supply
            and demand of electricity.
          </li>
        </ul>
        <ul className="list-disc leading-7 mb-3">
          <li>
            Job creation: The adoption of renewable energy systems through net
            metering can also create jobs in the renewable energy sector,
            contributing to the growth of the local economy.
          </li>
        </ul>
        <p>
          However, it is important to note that the benefits of net metering can
          vary depending on the specific policies and regulations in place, as
          well as the local electricity market conditions.
        </p>
      </div>
      <div className="flex items-center justify-center p-8">
        <Image src={illustration} className="w-full md:w-1/2 p-4" />
      </div>

      <div className="p-8">
        <h1 className="font-bold mb-8">Benefits of Hybrid Solar Plant</h1>
        <p className="mb-2">
          Hybrid solar plants offer a number of advantages over standalone solar
          power plants or other types of power plants. Here are some of the main
          advantages of hybrid solar plants
        </p>
        <ul className="list-disc leading-7 mb-3">
          <li>
            Financial savings: Net metering allows homeowners and businesses to
            generate their own electricity and receive credit for the excess
            electricity they generate, which can help to offset their
            electricity bills. This can result in significant financial savings
            over time.
          </li>
        </ul>
        <ul className="list-disc leading-7 mb-3">
          <li>
            Increased use of renewable energy: Net metering can encourage the
            adoption of renewable energy systems, such as solar panels, by
            making them more financially viable. This can help to reduce
            reliance on fossil fuels and promote a transition to cleaner energy
            sources.
          </li>
        </ul>
        <ul className="list-disc leading-7 mb-3">
          <li>
            Reduced greenhouse gas emissions: By promoting the use of renewable
            energy, net metering can help to reduce greenhouse gas emissions and
            mitigate the impacts of climate change.
          </li>
        </ul>
        <ul className="list-disc leading-7 mb-3">
          <li>
            Improved grid stability: Net metering can help to improve grid
            stability by reducing the strain on the grid during peak demand
            periods. This is because excess electricity generated by solar
            panels can be fed back into the grid, helping to balance the supply
            and demand of electricity.
          </li>
        </ul>
        <ul className="list-disc leading-7 mb-3">
          <li>
            Job creation: The adoption of renewable energy systems through net
            metering can also create jobs in the renewable energy sector,
            contributing to the growth of the local economy.
          </li>
        </ul>
        <p>
          However, it is important to note that the benefits of net metering can
          vary depending on the specific policies and regulations in place, as
          well as the local electricity market conditions.
        </p>
      </div>

      <div className="flex flex-col-reverse items-center justify-center w-full p-8 md:flex-row">
        <div className="w-full md:w-1/2 p-4">
          <h1 className="mb-8 font-bold text-center md:text-left">
            What is Net Metering?
          </h1>
          <p>
            Net metering is a billing arrangement that allows homeowners and
            businesses with renewable energy systems, such as solar panels, to
            receive credit for the excess electricity they generate and feed
            back into the grid. Under a net metering program, a bi-directional
            meter tracks the energy generated by the renewable energy system and
            the energy consumed by the customer. If the customer generates more
            electricity than they consume, the excess electricity is fed back
            into the grid and credited to their account. This credit can then be
            used to offset the cost of electricity that is consumed during
            periods when the renewable energy system is not generating
            electricity, such as at night or on cloudy days. Net metering
            policies vary by state and country, but it is a popular policy in
            many regions that encourage the adoption of renewable energy
            technologies.
          </p>
        </div>
        <div className="w-full md:w-1/2 p-4">
          <Image src={electroniccar} alt="leading" className="w-full" />
        </div>
      </div>

      <div className="p-8">
        <h1 className="font-bold mb-8">
          The main advantages of group net metering include:
        </h1>
        <ul className="list-disc leading-7 mb-3">
          <li>
            educed energy costs: Group net metering allows customers to share
            the benefits of a single renewable energy system, which can help to
            reduce energy costs for all members of the group.
          </li>
        </ul>
        <ul className="list-disc leading-7 mb-3">
          <li>
            Increased access to renewable energy: Group net metering can make it
            easier for households, small businesses, and community organizations
            to access and benefit from renewable energy sources, even if they
            are unable to install their own renewable energy systems.
          </li>
        </ul>
        <ul className="list-disc leading-7 mb-3">
          <li>
            Promotion of community energy: Group net metering can promote
            community energy by encouraging the development of shared renewable
            energy systems that benefit multiple customers and promote a sense
            of community ownership.
          </li>
        </ul>
        <ul className="list-disc leading-7 mb-3">
          <li>
            Reduced carbon emissions: Group net metering can help to reduce
            carbon emissions by promoting the use of renewable energy sources,
            such as solar or wind power, which have lower greenhouse gas
            emissions than fossil fuels.
          </li>
        </ul>
        <ul className="list-disc leading-7 mb-3">
          <li>
            In summary, group net metering is a policy that allows multiple
            customers or energy users to share the benefits of a single
            renewable energy system. It can help to lower energy costs, increase
            access to renewable energy, promote community energy, and reduce
            carbon emissions.
          </li>
        </ul>
      </div>

      <div className="flex flex-col items-center justify-center w-full p-8 md:flex-row">
        <div className="w-full md:w-1/2 p-4">
          <Image src={metering} alt="leading" className="w-full" />
        </div>
        <div className="w-full md:w-1/2 p-4">
          <h1 className="mb-8 font-bold text-center md:text-left">
            What is Net Metering?
          </h1>
          <p>
            Net metering is a billing arrangement that allows homeowners and
            businesses with renewable energy systems, such as solar panels, to
            receive credit for the excess electricity they generate and feed
            back into the grid. Under a net metering program, a bi-directional
            meter tracks the energy generated by the renewable energy system and
            the energy consumed by the customer. If the customer generates more
            electricity than they consume, the excess electricity is fed back
            into the grid and credited to their account. This credit can then be
            used to offset the cost of electricity that is consumed during
            periods when the renewable energy system is not generating
            electricity, such as at night or on cloudy days. Net metering
            policies vary by state and country, but it is a popular policy in
            many regions that encourage the adoption of renewable energy
            technologies.
          </p>
        </div>
      </div>

      <div className="p-8">
        <h1 className="font-bold mb-8">
          The main advantages of virtual net metering include:
        </h1>
        <ul className="list-disc leading-7 mb-3">
          <li>
            educed energy costs: Group net metering allows customers to share
            the benefits of a single renewable energy system, which can help to
            reduce energy costs for all members of the group.
          </li>
        </ul>
        <ul className="list-disc leading-7 mb-3">
          <li>
            Increased access to renewable energy: Group net metering can make it
            easier for households, small businesses, and community organizations
            to access and benefit from renewable energy sources, even if they
            are unable to install their own renewable energy systems.
          </li>
        </ul>
        <ul className="list-disc leading-7 mb-3">
          <li>
            Promotion of community energy: Group net metering can promote
            community energy by encouraging the development of shared renewable
            energy systems that benefit multiple customers and promote a sense
            of community ownership.
          </li>
        </ul>
        <ul className="list-disc leading-7 mb-3">
          <li>
            Reduced carbon emissions: Group net metering can help to reduce
            carbon emissions by promoting the use of renewable energy sources,
            such as solar or wind power, which have lower greenhouse gas
            emissions than fossil fuels.
          </li>
        </ul>
        <ul className="list-disc leading-7 mb-3">
          <li>
            In summary, group net metering is a policy that allows multiple
            customers or energy users to share the benefits of a single
            renewable energy system. It can help to lower energy costs, increase
            access to renewable energy, promote community energy, and reduce
            carbon emissions.
          </li>
        </ul>
      </div>

      <div className="flex items-center justify-center p-8">
        <Image src={minclude} className="w-full md:w-3/4 lg:w-1/2" />
      </div>

      <div className="p-8">
        <h1 className="font-bold mb-8">Benefits of Rooftop Solar</h1>
        <ul className="list-disc leading-7 mb-3">
          <li>
            educed energy costs: Group net metering allows customers to share
            the benefits of a single renewable energy system, which can help to
            reduce energy costs for all members of the group.
          </li>
        </ul>
        <ul className="list-disc leading-7 mb-3">
          <li>
            Increased access to renewable energy: Group net metering can make it
            easier for households, small businesses, and community organizations
            to access and benefit from renewable energy sources, even if they
            are unable to install their own renewable energy systems.
          </li>
        </ul>
        <ul className="list-disc leading-7 mb-3">
          <li>
            Promotion of community energy: Group net metering can promote
            community energy by encouraging the development of shared renewable
            energy systems that benefit multiple customers and promote a sense
            of community ownership.
          </li>
        </ul>
        <ul className="list-disc leading-7 mb-3">
          <li>
            Reduced carbon emissions: Group net metering can help to reduce
            carbon emissions by promoting the use of renewable energy sources,
            such as solar or wind power, which have lower greenhouse gas
            emissions than fossil fuels.
          </li>
        </ul>
        <ul className="list-disc leading-7 mb-3">
          <li>
            In summary, group net metering is a policy that allows multiple
            customers or energy users to share the benefits of a single
            renewable energy system. It can help to lower energy costs, increase
            access to renewable energy, promote community energy, and reduce
            carbon emissions.
          </li>
        </ul>
      </div>
    </div>
  );
};

export default Resource;
